# Generated by Django 4.2.6 on 2023-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Ведите имя', max_length=60, verbose_name='Имя')),
                ('author_surname', models.CharField(help_text='Ведите фамилию', max_length=70, unique=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Ведите название', max_length=30, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(db_index=True, help_text='Ведите название книги', max_length=50, unique=True, verbose_name='Книга')),
                ('description', models.TextField(help_text='Описание книги', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(db_index=True, default=100, help_text='Установите цену', verbose_name='Цена')),
                ('author', models.ManyToManyField(db_index=True, to='book_api.authormodel', verbose_name='Автор книги')),
                ('genre', models.ManyToManyField(db_index=True, to='book_api.genremodel', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
