# Generated by Django 4.2.6 on 2023-10-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(help_text='Описание книги, максимум 400 символов', verbose_name='Описание'),
        ),
    ]
